# Generated by Django 4.2.5 on 2023-09-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=221)),
                ('last_name', models.CharField(max_length=221)),
                ('email', models.EmailField(max_length=221)),
                ('subject', models.CharField(max_length=221)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
