# Generated by Django 4.2.5 on 2023-10-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='top_level_comment_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
