# Generated by Django 4.2.5 on 2023-09-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_company_skill_job_category_job_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
