# Generated by Django 4.2.5 on 2023-09-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_created_date_job_modified_date'),
        ('account', '0004_candidate_created_date_candidate_modified_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userexperience',
            name='position',
        ),
        migrations.AddField(
            model_name='userexperience',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.category'),
            preserve_default=False,
        ),
    ]
