# Generated by Django 4.2.5 on 2023-09-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userexperience_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexperience',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
