# Generated by Django 4.2.5 on 2023-10-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_candidate_is_deleted_usercompany_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(limit_choices_to={'type': 0}, on_delete=django.db.models.deletion.CASCADE, related_name='usercompanies', to=settings.AUTH_USER_MODEL),
        ),
    ]
